### ISSUE TITLE
issue with current project and release

### ISSUE THREAD

**Issue by elpie89** [techartorg/MXSPyCOM#13]
Hi, I get the last version and I made some test
running a simple print "hello world" on test file
give me back 
```
Error; filename: E:\Repository\mproject\src\test.py
-- Runtime error: 
Traceback (most recent call last):
AttributeError: 'module' object has no attribute 'suppress'
```
I wanted to try to open the visual studio project but it is not pushed
So I created mine importing the csproj of the repository

But I have this error back
![image](https://user-images.githubusercontent.com/4441151/70092040-aa955f00-161d-11ea-8b77-778a8f705de2.png)

**Comment by elpie89** [comment]
tested with visual studio 2017

**Comment by elpie89** [comment]
my bad you are no longer using visual studio, I thought was an error, I will use vscode to open the project

**Comment by JeffHanna** [comment]
I see the problem. In a brain-dead moment I forgot to switch my thinking from Python 3.x to Python 2.7. There is no suppress( ) method in the contextlib module in Python 2.7.

<Working on a fix>

**Comment by JeffHanna** [comment]
This issue has been fixed. Please grab the new 1.11 release.

https://github.com/techartorg/MXSPyCOM/releases/tag/1.11
